version: '3'
services:
  library:
    restart: on-failure
    container_name: "go-library"
    build: ./
    command: ./main
    ports:
      - "8080:8080"
    environment:
      DB_DRIVER: ${DB_DRIVER}  
      DB_PASSWORD: ${DB_PASSWORD}
      DB_USER: ${DB_USER}
      DB_NAME: ${DB_NAME}
      DB_PORT: ${DB_PORT}
      DB_HOST: ${DB_HOST}
    env_file:
      - .env
    depends_on:
      - db    
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}    
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    env_file:
      - .env
    ports:
      - "5432:5432"    
  migrator:
    image: migrate/migrate
    volumes:
      - ./migrations:/migrations
    entrypoint:
      [
        "migrate",
        "-path",
        "/migrations",
        "-database",
        "postgresql://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}?sslmode=disable",
      ]      
    command: ["up"]  
    depends_on:
      - db
    restart: on-failure  